In [10]:
import pandas as pd

info = pd.read_csv("tables/career_track_info.csv")
info

    track_course_id  track_id  course_id
0                 1         1          7
1                 2         1         21
2                 3         1         24
3                 4         1         16
4                 5         1         22
5                 6         1         14
6                 7         1         37
7                 8         1         32
8                11         2          7
9                12         2         23
10               13         2         21
11               14         2         14
12               15         2         35
13               16         2          3
14               17         2          5
15               18         2         11
16               21         3          7
17               22         3         46
18               23         3         42
19               24         3         23
20               25         3         13
21               26         3         39
22               27         3         21
23               28         3          3

In [11]:
enroll = pd.read_csv("tables/career_track_enrollments.csv")
enroll

      track_id  student_id date_enrolled
0            1      258800    2022-01-02
1            1      258807    2022-01-01
2            1      258818    2022-01-03
3            1      258822    2022-01-01
4            1      258833    2022-01-01
...        ...         ...           ...
7869         3      296791    2022-10-29
7870         3      296872    2022-10-30
7871         3      296900    2022-10-30
7872         3      296974    2022-10-31
7873         3      297018    2022-10-31

[7874 rows x 3 columns]

In [12]:
df = pd.DataFrame(data=[], columns=["action", "track_id", "n_students"])

df["track_id"] = [1, 2, 3] * 5
df

   action  track_id n_students
0     NaN         1        NaN
1     NaN         2        NaN
2     NaN         3        NaN
3     NaN         1        NaN
4     NaN         2        NaN
5     NaN         3        NaN
6     NaN         1        NaN
7     NaN         2        NaN
8     NaN         3        NaN
9     NaN         1        NaN
10    NaN         2        NaN
11    NaN         3        NaN
12    NaN         1        NaN
13    NaN         2        NaN
14    NaN         3        NaN

In [13]:
df["action"] = ["track enrollments"] * 3 + ["course exam attempts"] * 3 + ["course exam passed"] * 3 + ["final exam attempts"] * 3 + ["final exam passed"] * 3
df

                  action  track_id n_students
0      track enrollments         1        NaN
1      track enrollments         2        NaN
2      track enrollments         3        NaN
3   course exam attempts         1        NaN
4   course exam attempts         2        NaN
5   course exam attempts         3        NaN
6     course exam passed         1        NaN
7     course exam passed         2        NaN
8     course exam passed         3        NaN
9    final exam attempts         1        NaN
10   final exam attempts         2        NaN
11   final exam attempts         3        NaN
12     final exam passed         1        NaN
13     final exam passed         2        NaN
14     final exam passed         3        NaN

In [14]:
for i in range(3):
    df.loc[i, "n_students"] = len(enroll[enroll.track_id == i+1])

df

                  action  track_id n_students
0      track enrollments         1       2999
1      track enrollments         2       3915
2      track enrollments         3        960
3   course exam attempts         1        NaN
4   course exam attempts         2        NaN
5   course exam attempts         3        NaN
6     course exam passed         1        NaN
7     course exam passed         2        NaN
8     course exam passed         3        NaN
9    final exam attempts         1        NaN
10   final exam attempts         2        NaN
11   final exam attempts         3        NaN
12     final exam passed         1        NaN
13     final exam passed         2        NaN
14     final exam passed         3        NaN

In [15]:
exams = pd.read_csv("tables/student_exams.csv")
exams

       exam_attempt_id  student_id  exam_id  exam_passed date_exam_completed
0               173311      258803      475            1          2022-01-01
1               173332      258815      380            0          2022-01-01
2               173333      258815      380            1          2022-01-01
3               173335      258815      380            1          2022-01-01
4               173336      258815      380            0          2022-01-01
...                ...         ...      ...          ...                 ...
35354           244299      291837      757            0          2022-10-31
35355           244301      296709      709            1          2022-10-31
35356           244304      296402      710            1          2022-10-31
35357           244308      293965      696            1          2022-10-31
35358           244309      295106      826            1          2022-10-31

[35359 rows x 5 columns]

In [16]:
exam_info = pd.read_csv("tables/exam_info.csv")
exam_info

     exam_id  exam_category course_id track_id  exam_duration
0          1              1        36       \N             30
1          2              1        36       \N             30
2          3              1        36       \N             30
3          4              2        36       \N             80
4          5              1        46       \N            120
..       ...            ...       ...      ...            ...
902      957              2        52       \N             25
903      960              1        22       \N              9
904      961              2        22       \N             40
905      962              1        56       \N             15
906      963              2        56       \N             25

[907 rows x 5 columns]

In [20]:
course_exam_info = exam_info[exam_info.exam_category == 2].drop(["track_id", "exam_duration"], axis=1)
course_exam_info

     exam_id  exam_category course_id
3          4              2        36
8          9              2        46
13        18              2        21
17        22              2        23
22        27              2        37
..       ...            ...       ...
897      934              2         3
900      943              2        19
902      957              2        52
904      961              2        22
906      963              2        56

[257 rows x 3 columns]

In [21]:
exams_ext = pd.merge(exams, course_exam_info, on="exam_id", how="left")
exams_ext

,exam_attempt_id,student_id,exam_id,exam_passed,date_exam_completed,exam_category,course_id
0,173311,258803,475,1,2022-01-01,NaN,NaN
1,173332,258815,380,0,2022-01-01,NaN,NaN
2,173333,258815,380,1,2022-01-01,NaN,NaN
3,173335,258815,380,1,2022-01-01,NaN,NaN
4,173336,258815,380,0,2022-01-01,NaN,NaN
...,...,...,...,...,...,...,...
35354,244299,291837,757,0,2022-10-31,NaN,NaN
35355,244301,296709,709,1,2022-10-31,NaN,NaN
35356,244304,296402,710,1,2022-10-31,NaN,NaN
35357,244308,293965,696,1,2022-10-31,NaN,NaN
35358,244309,295106,826,1,2022-10-31,NaN,NaN

In [22]:
course_exams = exams_ext[exams_ext.exam_category == 2]
course_exams

,exam_attempt_id,student_id,exam_id,exam_passed,date_exam_completed,exam_category,course_id
17,173605,258878,371,0,2022-01-02,2.0,7
83,174122,259209,371,1,2022-01-04,2.0,7
125,174425,259258,371,1,2022-01-05,2.0,7
161,174639,258955,371,1,2022-01-06,2.0,7
174,174714,259268,443,1,2022-01-06,2.0,46
...,...,...,...,...,...,...,...
35298,244215,279562,538,1,2022-10-31,2.0,22
35301,244220,294590,715,0,2022-10-31,2.0,23
35309,244231,272510,663,1,2022-10-31,2.0,39
35323,244262,270607,758,1,2022-10-31,2.0,7
35337,244280,288923,711,0,2022-10-31,2.0,21

In [ ]:
course_exams = pd.merge(course_exams, enroll, on="student_id", how="left")
course_exams

,exam_attempt_id,student_id,exam_id,exam_passed,date_exam_completed,exam_category,course_id,track_id,date_enrolled
0,173605,258878,371,0,2022-01-02,2.0,7,1.0,2022-01-08
1,174122,259209,371,1,2022-01-04,2.0,7,2.0,2022-01-04
2,174425,259258,371,1,2022-01-05,2.0,7,1.0,2022-01-04
3,174639,258955,371,1,2022-01-06,2.0,7,1.0,2022-01-02
4,174639,258955,371,1,2022-01-06,2.0,7,2.0,2022-01-06
...,...,...,...,...,...,...,...,...,...
7708,244231,272510,663,1,2022-10-31,2.0,39,1.0,2022-05-02
7709,244231,272510,663,1,2022-10-31,2.0,39,2.0,2022-10-16
7710,244262,270607,758,1,2022-10-31,2.0,7,NaN,NaN
7711,244280,288923,711,0,2022-10-31,2.0,21,1.0,2022-09-05
7712,244280,288923,711,0,2022-10-31,2.0,21,3.0,2022-10-31

In [24]:
course_exams.date_exam_completed = pd.to_datetime(course_exams.date_exam_completed)
course_exams.date_enrolled = pd.to_datetime(course_exams.date_enrolled)
course_exams.dtypes

exam_attempt_id                 int64
student_id                      int64
exam_id                         int64
exam_passed                     int64
date_exam_completed    datetime64[ns]
exam_category                 float64
course_id                      object
track_id                      float64
date_enrolled          datetime64[ns]
dtype: object

In [33]:
def track_course_exam(track_id, only_pass=False):
    df = course_exams.dropna()
    track_courses = info[info.track_id == track_id].course_id.astype(str)
    df = df[df.track_id == track_id]
    if only_pass:
        df = df[df.exam_passed == 1]
    return df[(df.course_id.isin(track_courses)) & (df.date_enrolled <= df.date_exam_completed)]

for n, i in enumerate(range(3, 6)):
    df.loc[i, "n_students"] = track_course_exam(n+1).student_id.nunique()

for n, i in enumerate(range(6, 9)):
    df.loc[i, "n_students"] = track_course_exam(n+1, True).student_id.nunique()

df

                  action  track_id n_students
0      track enrollments         1       2999
1      track enrollments         2       3915
2      track enrollments         3        960
3   course exam attempts         1        383
4   course exam attempts         2        317
5   course exam attempts         3        163
6     course exam passed         1        344
7     course exam passed         2        299
8     course exam passed         3        148
9    final exam attempts         1        NaN
10   final exam attempts         2        NaN
11   final exam attempts         3        NaN
12     final exam passed         1        NaN
13     final exam passed         2        NaN
14     final exam passed         3        NaN

In [ ]:
track_exam_info = exam_info[exam_info.exam_category == 3]

track_exams = pd.merge(exams, track_exam_info, on="exam_id", how="left").dropna()
track_exams.track_id = track_exams.track_id.astype(int)
track_exams.dtypes

exam_attempt_id          int64
student_id               int64
exam_id                  int64
exam_passed              int64
date_exam_completed     object
exam_category          float64
course_id               object
track_id                 int64
exam_duration          float64
dtype: object

In [59]:
for n, i in enumerate(range(9, 12)):
    df.loc[i, "n_students"] = track_exams[track_exams.track_id == n+1].student_id.nunique()

df

                  action  track_id n_students
0      track enrollments         1       2999
1      track enrollments         2       3915
2      track enrollments         3        960
3   course exam attempts         1        383
4   course exam attempts         2        317
5   course exam attempts         3        163
6     course exam passed         1        344
7     course exam passed         2        299
8     course exam passed         3        148
9    final exam attempts         1         24
10   final exam attempts         2         33
11   final exam attempts         3         17
12     final exam passed         1        NaN
13     final exam passed         2        NaN
14     final exam passed         3        NaN

In [61]:

for n, i in enumerate(range(12, 15)):
    df.loc[i, "n_students"] = track_exams[(track_exams.exam_passed == 1) & (track_exams.track_id == n+1)].student_id.nunique()

df

                  action  track_id n_students
0      track enrollments         1       2999
1      track enrollments         2       3915
2      track enrollments         3        960
3   course exam attempts         1        383
4   course exam attempts         2        317
5   course exam attempts         3        163
6     course exam passed         1        344
7     course exam passed         2        299
8     course exam passed         3        148
9    final exam attempts         1         24
10   final exam attempts         2         33
11   final exam attempts         3         17
12     final exam passed         1         16
13     final exam passed         2         15
14     final exam passed         3         12

In [62]:
certs = pd.read_csv("tables/student_certificates.csv")
(certs[(certs.certificate_type == 2) & (certs.track_id == "1")].__len__(),
certs[(certs.certificate_type == 2) & (certs.track_id == "2")].__len__(),
certs[(certs.certificate_type == 2) & (certs.track_id == "3")].__len__())

(16, 15, 12)

In [63]:
df.to_csv("data/career_track_stats.csv", index=False)