In [38]:
import pandas as pd

df = pd.read_csv("data/engagement.csv")
df

       student_id engagement_date  paid
0          258815      2022-01-01     0
1          258822      2022-01-01     0
2          258798      2022-01-01     0
3          258807      2022-01-01     0
4          258809      2022-01-01     0
...           ...             ...   ...
68335      296997      2022-10-31     0
68336      291116      2022-10-31     1
68337      297053      2022-10-31     0
68338      271950      2022-10-31     1
68339      297055      2022-10-31     0

[68340 rows x 3 columns]

In [39]:
cohorts = df.groupby(["student_id", "paid"], as_index=False).engagement_date.min()
cohorts

       student_id  paid engagement_date
0          258798     0      2022-01-01
1          258800     1      2022-01-02
2          258803     1      2022-01-01
3          258804     0      2022-01-01
4          258807     0      2022-01-01
...           ...   ...             ...
20205      297048     0      2022-10-31
20206      297050     0      2022-10-31
20207      297052     0      2022-10-31
20208      297053     0      2022-10-31
20209      297055     0      2022-10-31

[20210 rows x 3 columns]

In [41]:
cohorts = cohorts.rename(columns={"engagement_date": "cohort"})
cohorts

       student_id  paid      cohort
0          258798     0  2022-01-01
1          258800     1  2022-01-02
2          258803     1  2022-01-01
3          258804     0  2022-01-01
4          258807     0  2022-01-01
...           ...   ...         ...
20205      297048     0  2022-10-31
20206      297050     0  2022-10-31
20207      297052     0  2022-10-31
20208      297053     0  2022-10-31
20209      297055     0  2022-10-31

[20210 rows x 3 columns]

In [43]:
df = pd.merge(df, cohorts, on=["student_id", "paid"])
df

       student_id engagement_date  paid      cohort
0          258815      2022-01-01     0  2022-01-01
1          258822      2022-01-01     0  2022-01-01
2          258798      2022-01-01     0  2022-01-01
3          258807      2022-01-01     0  2022-01-01
4          258809      2022-01-01     0  2022-01-01
...           ...             ...   ...         ...
68335      296997      2022-10-31     0  2022-10-31
68336      291116      2022-10-31     1  2022-09-18
68337      297053      2022-10-31     0  2022-10-31
68338      271950      2022-10-31     1  2022-04-26
68339      297055      2022-10-31     0  2022-10-31

[68340 rows x 4 columns]

In [56]:
df.cohort = pd.to_datetime(df.cohort).dt.strftime("%Y-%m")
df

       student_id engagement_date  paid   cohort
0          258815      2022-01-01     0  2022-01
1          258822      2022-01-01     0  2022-01
2          258798      2022-01-01     0  2022-01
3          258807      2022-01-01     0  2022-01
4          258809      2022-01-01     0  2022-01
...           ...             ...   ...      ...
68335      296997      2022-10-31     0  2022-10
68336      291116      2022-10-31     1  2022-09
68337      297053      2022-10-31     0  2022-10
68338      271950      2022-10-31     1  2022-04
68339      297055      2022-10-31     0  2022-10

[68340 rows x 4 columns]

In [61]:
df["period"] = pd.to_datetime(df.engagement_date).dt.month - pd.to_datetime(df.cohort).dt.month
df

       student_id engagement_date  paid   cohort  period
0          258815      2022-01-01     0  2022-01       0
1          258822      2022-01-01     0  2022-01       0
2          258798      2022-01-01     0  2022-01       0
3          258807      2022-01-01     0  2022-01       0
4          258809      2022-01-01     0  2022-01       0
...           ...             ...   ...      ...     ...
68335      296997      2022-10-31     0  2022-10       0
68336      291116      2022-10-31     1  2022-09       1
68337      297053      2022-10-31     0  2022-10       0
68338      271950      2022-10-31     1  2022-04       6
68339      297055      2022-10-31     0  2022-10       0

[68340 rows x 5 columns]

In [62]:
df.to_csv("data/cohorts.csv", index=False)